approved_organizations = [
    "Fruens Bøgegruppen",
    "Kalørgruppen",
    "Lindvedgruppen",
    "Munkebjerggruppen",
    "Næsbygruppen",
    "Skibhusgruppen",
    "Tagtækkergruppen",
    "Skt. Hansgruppen",
    "Aftengruppen Nord",
    "Aftengruppen Lavsenvænget",
    "Aftengruppen Risingsvej",
    "Aftengruppen Syd",
    "Byhuset",
    "Dyruphus",
    "Gurli Vibeke",
    "Lokalcenter Rosengård Kollektivboliger",
    "Plejehjemmet Marienlund Dagcenter",
    "Genoptræning Team Odense",
    "Genoptræningscenter Bolbro",
    "Genoptræningscenter Frederiksbroen, Nord",
    "Genoptræningscenter Frederiksbroen, Syd",
    "Genoptræningscenter Hollufgård",
    "Genoptræningscenter Sanderum",
    "Genoptræningscenter Øst",
    "Nat 1 Udkørende",
    "Danren Hjemmeservice A/S",
    "Flenco Rengøring ApS",
    "Svane Pleje, Syd APS",
    "Svane Pleje, Syd-Aften",
    "Svane Pleje, Syd-Dag",
    "Svane Pleje, Syd-Nat",
    "JJS Rent",
    "Servicegruppen Nord",
    "Servicegruppen Syd",
    "Benediktsgruppen",
    "Hunderupgruppen",
    "Lavsengruppen",
    "Mågebakkegruppen",
    "Rosengårdgruppen",
    "Stadiongruppen",
    "Stenløkkegruppen",
    "Åsumgruppen",
    "Dannesbohus Omsorgsafdeling",
    "Stadiongruppen Aftensygepleje",
    "Hunderupgruppen Aftensygepleje",
    "Sundhedsklinik Bolbro",
    "Sundhedsklinik Dalum",
    "Sundhedsklinik Havebæk",
    "Sundhedsklinik VIVO",
    "Botilbuddet Fælledvej",
    "Plejehjemmet Sukkerkogeriet",
    "Plejehjemmet Bolbro",
    "Plejehjemmet Ejlstrup",
    "Plejehjemmet Korsløkkehaven",
    "Plejehjemmet Sanderum",
    "Plejehjemmet Villestofte",
    "Plejehjemmet Ærtebjerghaven",
    "Plejehjemmet Albanigade",
    "Plejehjemmet Frederiksbroen",
    "Plejehjemmet Blomsterdalen",
    "Plejehjemmet Enrum",
    "Plejehjemmet Havebæk",
    "Plejehjemmet Herluf Trolle",
    "Plejehjemmet Hvenekilden",
    "Plejehjemmet Marienlund",
    "Plejehjemmet Rytterkasernen",
    "Plejehjemmet Skt. Hans Parken",
    "Plejehjemmet Svovlhatten",
    "Lokalcenter Rosengård",
    "Provstegårdshjemmet",
    "Plejehjemmet Ida Marie",
    "Fællesboligerne - Lille Glasvej",
    "Bofællesskabet Næsbyhus",
    "Tornbjerg Friplejehjem",
    "Bjerggårdshaven",
    "Autismetilbuddet Kelsbjergvej",
    "Bo- og Støttetilbuddet Hvedevangen",
    "Bo- og Støttetilbuddet Rytterkasernen",
    "Bo- og Støttetilbuddet Sprogøvej",
    "Bo- og Støttetilbuddet Æblegrenen",
    "Rødegårdsvej - Åhuset",
    "Bostedet Munkehatten",
    "Botilbuddet Bjørnemosen",
    "Botilbuddet Bækholmen",
    "Botilbuddet Sedenhuse",
    "Støttecentret Herluf Trolle",
    "Støttecentret Niels Bohr Parken",
    "Støttecentret Emilieparken",
    "Støttecentret Klostervej",
    "Støttecentret Poppelhaven",
    "Støttecentret Præstegårdshaven",
    "Team 5",
    "Ungefællesskabet Rømersvej",
    "Specialtilbuddet Grevenlund",
    "Specialtilbuddet Holluf Pile",
    "Specialtilbuddet Lindegården",
    "Specialtilbuddet Solfaldsvej",
    "Tornhuset Brunsegårdsvej",
    "Tornhuset Hvedevangen",
    "Tornhuset Peder Skrams Vej",
    "Tornhuset Syd",
    "Tornhuset Tornbjergvej",
    "Botilbuddet Fangelvej",
    "Botilbuddet Rydsåvej",
    "Kollegiet Roesskovsvej",
    "Tornbjerggård",
    "Vista Balboa",
    "Vista Hus",
    "Hjemmevejlederteamet",
    "Flexbostøtten",
    "Sociale Viceværter ÆHF",
    "Bostøtte Kontakten",
    "Bostøtte Rismarksvej",
    "Bostøtte Solfaldsvej"
]
